# Generated by Django 4.2.5 on 2023-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposexames',
            name='tipo',
            field=models.CharField(choices=[('I', 'Exame de Imagem'), ('S', 'Exame de Sangue')], max_length=2),
        ),
    ]
